#!/usr/bin/env python3
import argparse
import sys
import hashlib

parser = argparse.ArgumentParser(
    description='Use like a pipe get the hash in a file')
parser.add_argument('-o', dest='filename', required=True,
    help='The file where the hash is written to')
parser.add_argument('-a', dest='algorithm', default='sha256',
    choices=hashlib.algorithms_available,
    help='The hash alogrtithm to be used, default sha256')
parser.add_argument('-b', dest='buffsize', default=32768, type=int,
    help='Set the read buffer')
args = parser.parse_args()

m = getattr(hashlib, args.algorithm )()

while True:
    buffer=sys.stdin.buffer.raw.read(args.buffsize)
    m.update(buffer)
    sys.stdout.buffer.write(buffer)
    if not buffer:
        break

f = open(args.filename,'w')
f.write(m.hexdigest())
f.write('\n')
f.close()
